<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "operations"
 *
 * Auto generated by Extension Builder 2013-11-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Operations',
	'description' => 'Manage (firefighter) operations with detailed reports, images used resources or vehicles, google map view for locations and more. This extension was build to manage firefighter operations from "Freiwillige Feuerwehr Thale". Slider and lightbox for images. Possibly to use it for other reportable events like THW and so on.',
	'category' => 'plugin',
	'author' => 'Karsten Nowak',
	'author_email' => 'captnnowi@gmx.de',
	'author_company' => 'undkonsorten',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.8',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.1.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>