<?php

declare(strict_types=1);

namespace Kanow\Operations\Tests\Unit\Domain\Model\Type;

use Kanow\Operations\Domain\Model\Type;
use TYPO3\CMS\Extbase\Domain\Model\FileReference;
use TYPO3\CMS\Extbase\DomainObject\AbstractEntity;
use TYPO3\CMS\Extbase\Persistence\ObjectStorage;
use TYPO3\TestingFramework\Core\Unit\UnitTestCase;

/***************************************************************
 *  Copyright notice
 *
 *  (c) 2013 Karsten Nowak <captnnowi@gmx.de>
 *
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

/**
 * Test case for class \Kanow\Operations\Domain\Model\Type.
 *
 * @version $Id$
 * @copyright Copyright belongs to the respective authors
 * @license http://www.gnu.org/licenses/gpl.html GNU General Public License, version 3 or later
 *
 *
 * @author Karsten Nowak <captnnowi@gmx.de>
 */
class TypeTest extends UnitTestCase
{
    private Type $subject;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->subject = new Type();
    }

    /**
     * @test
     */
    public function isAbstractEntity(): void
    {
        self::assertInstanceOf(AbstractEntity::class, $this->subject);
    }

    /**
     * @test
     */
    public function titleCanBeSet(): void
    {
        $value = 'This is a type';
        $this->subject->setTitle($value);
        self::assertEquals($value, $this->subject->getTitle());
    }

    /**
     * @test
     */
    public function colorCanBeSet(): void
    {
        $value = '#aacc00';
        $this->subject->setColor($value);
        self::assertEquals($value, $this->subject->getColor());
    }

    /**
     * @test
     */
    public function imageCanBeSet(): void
    {
        $file = new FileReference();
        $image = new ObjectStorage();
        $image->attach($file);
        $this->subject->setImage($image);
        self::assertSame($image, $this->subject->getImage());
    }

}
