<?php

declare(strict_types=1);

namespace Kanow\Operations\Tests\Unit\Domain\Model\Vehicle;
use Kanow\Operations\Domain\Model\Vehicle;
use TYPO3\CMS\Extbase\Domain\Model\FileReference;
use TYPO3\CMS\Extbase\Persistence\ObjectStorage;
use TYPO3\TestingFramework\Core\Unit\UnitTestCase;
/***************************************************************
 *  Copyright notice
 *
 *  (c) 2013 Karsten Nowak <captnnowi@gmx.de>
 *  			
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

/**
 * Test case for class \Kanow\Operations\Domain\Model\Vehicle.
 *
 * @version $Id$
 * @copyright Copyright belongs to the respective authors
 * @license http://www.gnu.org/licenses/gpl.html GNU General Public License, version 3 or later
 *
 * @package TYPO3
 * @subpackage Operations
 *
 * @author Karsten Nowak <captnnowi@gmx.de>
 */
class VehicleTest extends UnitTestCase {

    private Vehicle $subject;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->subject = new Vehicle();
    }

    /**
     * @test
     */
    public function titleCanBeSet(): void
    {
        $value = 'This is the tile';
        $this->subject->setTitle($value);
        $this->assertEquals($value, $this->subject->getTitle());
    }

    /**
     * @test
     */
    public function shortCanBeSet(): void
    {
        $value = 'Short title';
        $this->subject->setShort($value);
        $this->assertEquals($value, $this->subject->getShort());
    }

    /**
     * @test
     */
    public function descriptionCanBeSet(): void
    {
        $value = 'This is the description.';
        $this->subject->setDescription($value);
        $this->assertEquals($value, $this->subject->getDescription());
    }

    /**
     * @test
     */
    public function mediaCanBeSet(): void
    {
        $file = new FileReference();
        $media = new ObjectStorage();
        $media->attach($file);
        $this->subject->setMedia($media);
        $this->assertSame($media, $this->subject->getMedia());
        $this->assertSame($file, $this->subject->getFirstMedia());
    }

    /**
     * @test
     */
    public function linkCanBeSet(): void
    {
        $value = 'This is a link';
        $this->subject->setLink($value);
        $this->assertEquals($value, $this->subject->getLink());
    }
}