imports:
    - { resource: Backend/Widgets/OperationsWidgets.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kanow\Operations\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'
